blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://atl.pw/discord
    about: If you're having issues with the launcher or running Minecraft, please post in our Discord.