# suppress inspection "UnusedProperty" for whole file
#
# ATLauncher - https://github.com/ATLauncher/ATLauncher
# Copyright (C) 2013-2020 ATLauncher
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# This inherits from
# ./Light.properties
# ./ATLauncherLaf.properties
# https://raw.githubusercontent.com/JFormDesigner/FlatLaf/master/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatDarkLaf.properties
# https://raw.githubusercontent.com/JFormDesigner/FlatLaf/master/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties

#---- variables ----
rosewater=#dc8a78
flamingo=#dd7878
mauve=#8839ef
pink=#ea76cb
maroon=#e64553
red=#d20f39
peach=#fe640b
yellow=#df8e1d
green=#40a02b
teal=#179299
blue=#1e66f5
sky=#04a5e5
sapphire=#209fb5
lavender=#7287fd
crust=#dce0e8
mantle=#e6e9ef
base=#eff1f5
surface0=#ccd0da
surface1=#bcc0cc
surface2=#acb0be
overlay0=#9ca0b0
overlay1=#8c8fa1
overlay2=#7c7f93
text=#4c4f69
subtext0=#6c6f85
subtext1=#5c5f77
accentColor=#8839ef
secondaryAccentColor=#df8e1d
primaryForeground=#4c4f69
primaryBackground=#eff1f5
secondaryBackground=#ccd0da
inactiveBackground=#dce0e8
panelForeground=#4c4f69
panelBackground=#e6e9ef
toolbarBackground=#dce0e8
hoverBackground=#ccced7
selectionBackground=#d8dae1
selectionInactiveBackground=#eff1f5
borderColor=#dce0e8
separatorColor=#ccd0da
searchMatchBackground=#8839ef4d
textFieldBackground=#bcc0cc
gitLogBackground=#8839ef0d
dragAndDropBackground=#8839ef26

#---- override base variables ----
@background=$primaryBackground
@foreground=$primaryForeground
separatorColor=$separatorColor
buttonBackground=$primaryBackground

#---- checkbox ----
CheckBox.icon.background=$primaryBackground
CheckBox.icon.disabledBackground=$panelBackground
CheckBox.icon.borderColor=$borderColor
CheckBox.icon.disabledBorderColor=$secondaryBackground
CheckBox.icon.focusedBorderColor=$accentColor
CheckBox.icon.focusColor=$accentColor
CheckBox.icon.disabledCheckmarkColor=$primaryBackground
CheckBox.icon.selectedBackground=$primaryBackground
CheckBox.icon.selectedBorderColor=$accentColor
CheckBox.icon.checkmarkColor=$accentColor
CheckBox.icon.focusedSelectedBorderColor=$primaryForeground

#---- console ----
Console.LogType.debug=$green
Console.LogType.error=$red
Console.LogType.info=$accentColor
Console.LogType.warn=$yellow
Console.LogType.default=$primaryForeground

#---- tab color fix ----
TabbedPane.inactiveUnderlineColor=$accentColor

#---- news color fix ----
News.headerColor=$accentColor
News.linkColor=$accentColor

#---- hover line border fix ----
HoverLineBorder.borderColor=$accentColor

#---- all the things ----
*.foreground=$primaryForeground
*.background=$primaryBackground
*.disabledBackground=$primaryBackground
*.inactiveBackground=$primaryBackground
*.selectionBackground=$selectionBackground
*.selectionForeground=$primaryForeground
*.selectionInactiveBackground=$selectionInactiveBackground
*.selectionInactiveForeground=$primaryForeground
*.separatorColor=$separatorColor
*.borderColor=$borderColor
*.focusColor=$accentColor
*.infoForeground=$subtext0
ActionButton.hoverBackground=$hoverBackground
ActionButton.pressedBackground=$hoverBackground
Banner.errorBackground=#d20f391a
Banner.errorBorderColor=#d20f3926
Banner.errorForeground=$primaryForeground
Banner.informativeBackground=#1e66f51a
Banner.informativeBorderColor=#1e66f51a
Banner.informativeForeground=$primaryForeground
Banner.warningBackground=#fe640b1a
Banner.warningBorderColor=#fe640b1a
Banner.warningForeground=$primaryForeground
Bookmark.Mnemonic.iconBackground=$secondaryBackground
Bookmark.Mnemonic.iconBorderColor=$accentColor
Bookmark.Mnemonic.iconForeground=$primaryForeground
Bookmark.MnemonicAssigned.background=$secondaryBackground
Bookmark.MnemonicAssigned.borderColor=$secondaryAccentColor
Bookmark.MnemonicAssigned.foreground=$primaryForeground
Bookmark.MnemonicCurrent.background=$selectionBackground
Bookmark.MnemonicCurrent.borderColor=$accentColor
Bookmark.MnemonicCurrent.foreground=$primaryForeground
Bookmark.iconBackground=$accentColor
Borders.ContrastBorderColor=$separatorColor
Borders.color=$borderColor
Button.background=$panelBackground
Button.default.endBackground=$accentColor
Button.default.endBorderColor=$accentColor
Button.default.focusColor=$accentColor
Button.default.focusedBorderColor=$accentColor
Button.default.foreground=$crust
Button.default.startBackground=$accentColor
Button.default.startBorderColor=$accentColor
Button.disabledBorderColor=$secondaryBackground
Button.endBackground=$secondaryBackground
Button.endBorderColor=$secondaryBackground
Button.focusedBorderColor=$secondaryBackground
Button.foreground=$primaryForeground
Button.startBackground=$secondaryBackground
Button.startBorderColor=$secondaryBackground
CheckBox.background=$panelBackground
ComboBox.ArrowButton.background=$secondaryBackground
ComboBox.ArrowButton.disabledIconColor=$lavender
ComboBox.ArrowButton.iconColor=$accentColor
ComboBox.ArrowButton.nonEditableBackground=$secondaryBackground
ComboBox.modifiedItemForeground=$accentColor
ComboBox.nonEditableBackground=$secondaryBackground
ComboBox.selectionBackground=$selectionBackground
CompletionPopup.matchForeground=$accentColor
CompletionPopup.selectionBackground=$surface1
CompletionPopup.selectionInactiveBackground=$surface1
Component.borderColor=$borderColor
Component.disabledBorderColor=$selectionBackground
Component.errorFocusColor=$red
Component.focusColor=$accentColor
Component.focusedBorderColor=$selectionBackground
Component.iconColor=$primaryForeground
Component.inactiveErrorFocusColor=$red
Component.inactiveWarningFocusColor=$yellow
Component.warningFocusColor=$yellow
Component.infoForeground=$subtext0
Counter.background=$accentColor
Counter.foreground=$primaryBackground
DefaultTabs.background=$panelBackground
DefaultTabs.hoverBackground=$primaryBackground
DefaultTabs.underlinedTabBackground=$panelBackground
DragAndDrop.borderColor=$selectionBackground
DragAndDrop.rowBackground=$dragAndDropBackground
DragAndDrop.areaForeground=$primaryForeground
DragAndDrop.areaBackground=$panelBackground
DragAndDrop.areaBorderColor=$accentColor
Editor.Toolbar.borderColor=$separatorColor
Editor.background=$primaryBackground
Editor.shortcutForeground=$accentColor
EditorPane.splitBorder=$separatorColor
EditorTabs.background=$primaryBackground
EditorTabs.hoverBackground=$selectionBackground
EditorTabs.underTabsBorderColor=$separatorColor
EditorTabs.underlineColor=$accentColor
EditorTabs.underlinedTabBackground=$panelBackground
EditorTabs.unselectedBlend=0.9
FileColor.Blue=#e5eaf5
FileColor.Green=#e6edeb
FileColor.Orange=#f0eaea
FileColor.Rose=#eee6ec
FileColor.Violet=#e9ecf6
FileColor.Yellow=#eeecea
Label.background=$panelBackground
Label.selectedForeground=$selectionBackground
Link.activeForeground=$accentColor
Link.hoverForeground=$accentColor
Link.pressedForeground=$secondaryAccentColor
Link.visitedForeground=$secondaryAccentColor
List.Button.leftRightInset=8
List.Button.separatorInset=4
List.Button.hoverBackground=$hoverBackground
List.background=$panelBackground
List.border=4,0,4,0
List.hoverBackground=$hoverBackground
List.rowHeight=24
List.selectionInactiveBackground=$selectionInactiveBackground
MainToolbar.Dropdown.hoverBackground=$hoverBackground
MainToolbar.Dropdown.maxWidth=350
MainToolbar.Dropdown.pressedBackground=$hoverBackground
MainToolbar.Icon.hoverBackground=$hoverBackground
MainToolbar.Icon.insets=5,5,5,5
MainToolbar.Icon.pressedBackground=$hoverBackground
MainToolbar.background=$toolbarBackground
MainToolbar.inactiveBackground=$panelBackground
MainWindow.Tab.background=$toolbarBackground
MainWindow.Tab.borderColor=$toolbarBackground
MainWindow.Tab.selectedBackground=$panelBackground
MainWindow.Tab.selectedForeground=$primaryForeground
MainWindow.Tab.hoverBackground=$hoverBackground
MainWindow.Tab.selectedInactiveBackground=$primaryBackground
MainWindow.Tab.separatorColor=$separatorColor
MemoryIndicator.allocatedBackground=$surface0
MemoryIndicator.usedBackground=$surface1
Notification.ToolWindow.errorBackground=$primaryBackground
Notification.ToolWindow.errorBorderColor=$red
Notification.ToolWindow.errorForeground=$primaryForeground
Notification.ToolWindow.informativeBackground=$primaryBackground
Notification.ToolWindow.informativeBorderColor=$secondaryAccentColor
Notification.ToolWindow.informativeForeground=$primaryForeground
Notification.ToolWindow.warningBackground=$primaryBackground
Notification.ToolWindow.warningBorderColor=$peach
Notification.ToolWindow.warningForeground=$primaryForeground
Notification.background=$panelBackground
Notification.borderColor=$borderColor
Notification.errorBackground=$primaryBackground
Notification.errorBorderColor=$red
Notification.errorForeground=$primaryForeground
NotificationsToolwindow.newNotification.background=$primaryBackground
NotificationsToolwindow.newNotification.hoverBackground=$hoverBackground
Panel.foreground=$panelForeground
Panel.background=$panelBackground
PasswordField.background=$secondaryBackground
Plugins.Button.installBackground=$primaryBackground
Plugins.Button.installBorderColor=$secondaryAccentColor
Plugins.Button.installFillBackground=$secondaryAccentColor
Plugins.Button.installFillForeground=$primaryBackground
Plugins.Button.installFocusedBackground=$primaryBackground
Plugins.Button.installForeground=$secondaryAccentColor
Plugins.Button.updateBackground=$accentColor
Plugins.Button.updateBorderColor=$accentColor
Plugins.Button.updateForeground=$primaryBackground
Plugins.SearchField.background=$panelBackground
Plugins.SectionHeader.foreground=$primaryForeground
Plugins.Tab.hoverBackground=$hoverBackground
Plugins.Tab.selectedBackground=$selectionBackground
Plugins.Tab.selectedForeground=$primaryForeground
Plugins.borderColor=$borderColor
Plugins.hoverBackground=$hoverBackground
Plugins.lightSelectionBackground=$selectionBackground
Plugins.tagBackground=$panelBackground
Popup.Advertiser.background=$panelBackground
Popup.Advertiser.fontSizeOffset=-1
Popup.Advertiser.foreground=$text
Popup.Header.activeBackground=$panelBackground
Popup.Header.inactiveBackground=$panelBackground
Popup.borderColor=$separatorColor
Popup.borderWidth=1
Popup.inactiveBorderColor=$separatorColor
ProgressBar.failedColor=$red
ProgressBar.failedEndColor=$maroon
ProgressBar.indeterminateEndColor=$secondaryAccentColor
ProgressBar.indeterminateStartColor=$accentColor
ProgressBar.passedColor=$green
ProgressBar.passedEndColor=$teal
ProgressBar.progressColor=$accentColor
ProgressBar.trackColor=$selectionBackground
RadioButton.background=$panelBackground
RunWidget.background=$secondaryBackground
RunWidget.foreground=$text
RunWidget.iconColor=$primaryForeground
RunWidget.pressedBackground=$green
RunWidget.separatorColor=$separatorColor
RunWidget.stopBackground=$red
ScrollBar.thumbBorderColor=$surface0
ScrollBar.thumbColor=$surface0
ScrollBar.hoverThumbColor=$surface1
ScrollBar.hoverThumbBorderColor=$surface1
ScrollBar.Mac.thumbBorderColor=$surface0
ScrollBar.Mac.thumbColor=$surface0
ScrollBar.Mac.hoverThumbColor=$surface1
ScrollBar.Mac.hoverThumbBorderColor=$surface1
SearchEverywhere.SearchField.background=$secondaryBackground
SearchEverywhere.Tab.selectedBackground=$secondaryBackground
SearchEverywhere.Tab.selectedForeground=$primaryForeground
SearchMatch.endBackground=$searchMatchBackground
SearchMatch.startBackground=$searchMatchBackground
SegmentedButton.focusedSelectedButtonColor=$secondaryBackground
SegmentedButton.selectedButtonColor=$secondaryBackground
SegmentedButton.selectedEndBorderColor=$secondaryBackground
SegmentedButton.selectedStartBorderColor=$secondaryBackground
Separator.separatorColor=$separatorColor
SidePanel.background=$panelBackground
Slider.background=$panelBackground
StatusBar.Breadcrumbs.chevronInset=0
StatusBar.background=$panelBackground
StatusBar.borderColor=$borderColor
StatusBar.hoverBackground=$hoverBackground
TabbedPane.background=$panelBackground
TabbedPane.contentAreaColor=$borderColor
TabbedPane.focusColor=$selectionBackground
TabbedPane.hoverColor=$hoverBackground
TabbedPane.tabHeight=40
TabbedPane.tabSelectionArc=4
TabbedPane.underlineColor=$accentColor
Table.gridColor=$hoverBackground
Table.hoverBackground=$selectionBackground
Table.lightSelectionBackground=$secondaryBackground
TableHeader.bottomSeparatorColor=$primaryBackground
TextArea.background=$panelBackground
TextField.background=$secondaryBackground
TextField.selectionBackground=$textFieldBackground
ToggleButton.buttonColor=$primaryForeground
ToggleButton.offBackground=$selectionBackground
ToggleButton.offForeground=$hoverBackground
ToggleButton.onBackground=$green
ToggleButton.onForeground=$hoverBackground
ToolBar.background=$panelBackground
ToolBar.borderHandleColor=$secondaryAccentColor
ToolWindow.Button.hoverBackground=$hoverBackground
ToolWindow.Button.selectedBackground=$hoverBackground
ToolWindow.Button.selectedForeground=$primaryForeground
ToolWindow.Header.background=$panelBackground
ToolWindow.Header.borderColor=$borderColor
ToolWindow.Header.inactiveBackground=$panelBackground
ToolWindow.HeaderTab.hoverBackground=$surface0
ToolWindow.HeaderTab.inactiveUnderlineColor=$text
ToolWindow.HeaderTab.underlineColor=$accentColor
ToolWindow.Stripe.background=$panelBackground
ToolWindow.background=$panelBackground
Tree.background=$panelBackground
Tree.border=4,12,4,12
Tree.foreground=$primaryForeground
Tree.hoverBackground=$hoverBackground
Tree.modifiedItemForeground=$accentColor
Tree.rowHeight=24
Tree.selectionBackground=$selectionBackground
Tree.selectionInactiveBackground=$selectionBackground
UiDesigner.Panel.background=$panelBackground
UiDesigner.Preview.background=$panelBackground
ValidationTooltip.errorBackground=$panelBackground
ValidationTooltip.errorBorderColor=$red
ValidationTooltip.warningBackground=$panelBackground
ValidationTooltip.warningBorderColor=$secondaryAccentColor
VersionControl.FileHistory.Commit.selectedBranchBackground=$secondaryBackground
VersionControl.GitLog.headIconColor=$secondaryAccentColor
VersionControl.GitLog.localBranchIconColor=$green
VersionControl.GitLog.otherIconColor=$teal
VersionControl.GitLog.remoteBranchIconColor=$secondaryAccentColor
VersionControl.GitLog.tagIconColor=$accentColor
VersionControl.Log.Commit.currentBranchBackground=$gitLogBackground
VersionControl.Log.Commit.hoveredBackground=$hoverBackground
VersionControl.Log.Commit.selectionInactiveBackground=$hoverBackground
VersionControl.RefLabel.foreground=$primaryForeground
WelcomeScreen.Projects.actions.background=$hoverBackground
WelcomeScreen.Projects.background=$hoverBackground
WelcomeScreen.Projects.selectionBackground=$secondaryBackground
WelcomeScreen.Projects.selectionInactiveBackground=$secondaryBackground
WelcomeScreen.SidePanel.background=$panelBackground
WelcomeScreen.separatorColor=$separatorColor