# suppress inspection "UnusedProperty" for whole file
#
# ATLauncher - https://github.com/ATLauncher/ATLauncher
# Copyright (C) 2013-2020 ATLauncher
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# This inherits from
# ./CatppuccinMacchiato.properties
# ./Dark.properties
# ./ATLauncherLaf.properties
# https://raw.githubusercontent.com/JFormDesigner/FlatLaf/master/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatDarkLaf.properties
# https://raw.githubusercontent.com/JFormDesigner/FlatLaf/master/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties

#---- variables ----
rosewater=#f2d5cf
flamingo=#eebebe
mauve=#ca9ee6
pink=#f4b8e4
maroon=#ea999c
red=#e78284
peach=#ef9f76
yellow=#e5c890
green=#a6d189
teal=#81c8be
blue=#8caaee
sky=#99d1db
sapphire=#85c1dc
lavender=#babbf1
crust=#232634
mantle=#292c3c
base=#303446
surface0=#414559
surface1=#51576d
surface2=#626880
overlay0=#737994
overlay1=#838ba7
overlay2=#949cbb
text=#c6d0f5
subtext0=#a5adce
subtext1=#b5bfe2
accentColor=#ca9ee6
secondaryAccentColor=#e5c890
primaryForeground=#c6d0f5
primaryBackground=#303446
secondaryBackground=#414559
inactiveBackground=#232634
panelForeground=#c6d0f5
panelBackground=#292c3c
toolbarBackground=#232634
hoverBackground=#4f5369
selectionBackground=#44495d
selectionInactiveBackground=#303446
borderColor=#303446
separatorColor=#414559
searchMatchBackground=#ca9ee6
textFieldBackground=#626880
gitLogBackground=#ca9ee60d
dragAndDropBackground=#ca9ee626