# suppress inspection "UnusedProperty" for whole file
#
# ATLauncher - https://github.com/ATLauncher/ATLauncher
# Copyright (C) 2013-2020 ATLauncher
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

# This inherits from
# ./CatppuccinMacchiato.properties
# ./Dark.properties
# ./ATLauncherLaf.properties
# https://raw.githubusercontent.com/JFormDesigner/FlatLaf/master/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatDarkLaf.properties
# https://raw.githubusercontent.com/JFormDesigner/FlatLaf/master/flatlaf-core/src/main/resources/com/formdev/flatlaf/FlatLaf.properties

#---- variables ----
rosewater=#f5e0dc
flamingo=#f2cdcd
mauve=#cba6f7
pink=#f5c2e7
maroon=#eba0ac
red=#f38ba8
peach=#fab387
yellow=#f9e2af
green=#a6e3a1
teal=#94e2d5
blue=#89b4fa
sky=#89dceb
sapphire=#74c7ec
lavender=#b4befe
crust=#11111b
mantle=#181825
base=#1e1e2e
surface0=#313244
surface1=#45475a
surface2=#585b70
overlay0=#6c7086
overlay1=#7f849c
overlay2=#9399b2
text=#cdd6f4
subtext0=#a6adc8
subtext1=#bac2de
accentColor=#cba6f7
secondaryAccentColor=#f9e2af
primaryForeground=#cdd6f4
primaryBackground=#1e1e2e
secondaryBackground=#313244
inactiveBackground=#11111b
panelForeground=#cdd6f4
panelBackground=#181825
toolbarBackground=#11111b
hoverBackground=#414356
selectionBackground=#353749
selectionInactiveBackground=#1e1e2e
borderColor=#1e1e2e
separatorColor=#313244
searchMatchBackground=#cba6f7
textFieldBackground=#585b70
gitLogBackground=#cba6f70d
dragAndDropBackground=#cba6f726