name: Automerge master into develop

on:
  push:
    branches:
      - master

jobs:
  update-cms-master:
    name: Merge master into develop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge
        uses: richard-scott/automerger-action@v1.0.4
        with:
          github_token: ${{ github.token }}
          source: "master"
          target: "develop"
          message: "${{ github.event.commits[0].message }}"
          webhook_url: ""
